import type { MonsterDna } from "./dna";

export type MonsterArchetype = {
  id: string;
  label: string;
  mark: string;
  summary: string;
  dna: MonsterDna;
};

export const MONSTER_ARCHETYPES: MonsterArchetype[] = [
  {
    id: "gorilla",
    label: "Gorilla-like",
    mark: "GRL",
    summary: "Large, strong omnivore that stays with one companion.",
    dna: {
      body: "biped",
      legs: 2,
      legShape: "stubby",
      eyes: 2,
      mouth: "fangs",
      size: "large",
      build: "sturdy",
      color: "cocoa",
      accent: "cream",
      pattern: "patches",
      horns: "none",
      ears: "round",
      tail: "none",
      adaptation: "none",
      diet: "omnivore",
      breathing: "lungs",
      social: "pair",
      mesh: "smooth",
    },
  },
  {
    id: "shark",
    label: "Shark-like",
    mark: "SHK",
    summary: "A solitary ocean hunter with gills and powerful fins.",
    dna: {
      body: "aquatic",
      legs: 0,
      legShape: "flippers",
      eyes: 2,
      mouth: "fangs",
      size: "large",
      build: "lean",
      color: "glacier",
      accent: "white",
      pattern: "stripes",
      horns: "none",
      ears: "none",
      tail: "fin",
      adaptation: "fins",
      diet: "carnivore",
      breathing: "gills",
      social: "solitary",
      mesh: "smooth",
    },
  },
  {
    id: "seagull",
    label: "Seagull-like",
    mark: "GUL",
    summary: "A small winged omnivore that travels in a noisy pack.",
    dna: {
      body: "avian",
      legs: 2,
      legShape: "clawed",
      eyes: 2,
      mouth: "beak",
      size: "small",
      build: "lean",
      color: "moon",
      accent: "lemon",
      pattern: "patches",
      horns: "none",
      ears: "none",
      tail: "tuft",
      adaptation: "wings",
      diet: "omnivore",
      breathing: "lungs",
      social: "pack",
      mesh: "smooth",
    },
  },
  {
    id: "rhino",
    label: "Rhino-like",
    mark: "RHN",
    summary: "A large solitary herbivore with hooves and a nose horn.",
    dna: {
      body: "rhino",
      legs: 4,
      legShape: "hoof",
      eyes: 2,
      mouth: "snout",
      size: "large",
      build: "sturdy",
      color: "moon",
      accent: "cream",
      pattern: "plain",
      horns: "rhino",
      ears: "fan",
      tail: "tuft",
      adaptation: "plates",
      diet: "herbivore",
      breathing: "lungs",
      social: "solitary",
      mesh: "smooth",
    },
  },
  {
    id: "raptor",
    label: "Raptor-like",
    mark: "RPT",
    summary: "A fast clawed carnivore that hunts with a small pack.",
    dna: {
      body: "saurian",
      legs: 2,
      legShape: "clawed",
      eyes: 3,
      mouth: "fangs",
      size: "medium",
      build: "lean",
      color: "ember",
      accent: "lemon",
      pattern: "stripes",
      horns: "spikes",
      ears: "pointed",
      tail: "club",
      adaptation: "plates",
      diet: "carnivore",
      breathing: "lungs",
      social: "pack",
      mesh: "smooth",
    },
  },
  {
    id: "dragon",
    label: "Dragon-like",
    mark: "DRG",
    summary: "A huge winged predator; dangerous enough to live alone.",
    dna: {
      body: "saurian",
      legs: 4,
      legShape: "clawed",
      eyes: 4,
      mouth: "fangs",
      size: "large",
      build: "sturdy",
      color: "midnight",
      accent: "cherry",
      pattern: "scales",
      horns: "spikes",
      ears: "pointed",
      tail: "club",
      adaptation: "wings",
      diet: "carnivore",
      breathing: "lungs",
      social: "solitary",
      mesh: "smooth",
    },
  },
  {
    id: "beetle",
    label: "Beetle-like",
    mark: "BTL",
    summary: "A tiny six-legged herbivore protected by a shell army.",
    dna: {
      body: "round",
      legs: 6,
      legShape: "clawed",
      eyes: 4,
      mouth: "smile",
      size: "small",
      build: "sturdy",
      color: "lime",
      accent: "violet",
      pattern: "spots",
      horns: "single",
      ears: "none",
      tail: "none",
      adaptation: "shell",
      diet: "herbivore",
      breathing: "lungs",
      social: "army",
      mesh: "smooth",
    },
  },
  {
    id: "octopus",
    label: "Octopus-like",
    mark: "OCT",
    summary: "A clever eight-limbed omnivore that breathes with gills.",
    dna: {
      body: "bean",
      legs: 8,
      legShape: "flippers",
      eyes: 2,
      mouth: "beak",
      size: "medium",
      build: "balanced",
      color: "bubblegum",
      accent: "aqua",
      pattern: "spots",
      horns: "none",
      ears: "none",
      tail: "none",
      adaptation: "fins",
      diet: "omnivore",
      breathing: "gills",
      social: "solitary",
      mesh: "smooth",
    },
  },
  {
    id: "frog",
    label: "Frog-like",
    mark: "FRG",
    summary: "A small amphibious omnivore with springy legs and friends.",
    dna: {
      body: "bean",
      legs: 4,
      legShape: "springy",
      eyes: 2,
      mouth: "smile",
      size: "small",
      build: "balanced",
      color: "moss",
      accent: "lemon",
      pattern: "spots",
      horns: "none",
      ears: "round",
      tail: "none",
      adaptation: "fins",
      diet: "omnivore",
      breathing: "both",
      social: "pack",
      mesh: "smooth",
    },
  },
  {
    id: "boar",
    label: "Boar-like",
    mark: "BOR",
    summary: "A tough tusked omnivore that moves with a family group.",
    dna: {
      body: "pig",
      legs: 4,
      legShape: "hoof",
      eyes: 2,
      mouth: "tusks",
      size: "medium",
      build: "sturdy",
      color: "cocoa",
      accent: "peach",
      pattern: "stripes",
      horns: "none",
      ears: "floppy",
      tail: "curly",
      adaptation: "plates",
      diet: "omnivore",
      breathing: "lungs",
      social: "pair",
      mesh: "smooth",
    },
  },
];
