/**
 * Compatibility surface for the browser. The single source of truth for the
 * DNA codec, trait tables and derived traits now lives in `@monsters/game-core`
 * so the API and the client can never disagree about a genome.
 */
export {
  ACCENT_COLORS,
  ADAPTATIONS,
  BODY_SHAPES,
  DEFAULT_MONSTER_DNA,
  DIETS,
  EAR_SHAPES,
  EYE_COUNTS,
  HORN_SHAPES,
  LEG_COUNTS,
  LEG_SHAPES,
  MESH_STYLES,
  MONSTER_BUILDS,
  MONSTER_COLORS,
  MONSTER_SIZES,
  MOUTH_SHAPES,
  PATTERNS,
  RESPIRATIONS,
  SOCIAL_BEHAVIORS,
  SMOOTH_HORN_SHAPES,
  SMOOTH_PATTERNS,
  TAIL_SHAPES,
  canMonsterEatPlants,
  canMonsterHunt,
  canMonsterSwim,
  decodeMonsterDna,
  encodeMonsterDna,
  getAccentColor,
  getMonsterBuildScale,
  getMonsterColor,
  getMonsterFollowerCount,
  getMonsterSizeScale,
} from "@monsters/game-core";

export type {
  AccentColor,
  Adaptation,
  BodyShape,
  Diet,
  EarShape,
  EyeCount,
  HornShape,
  LegCount,
  LegShape,
  MeshStyle,
  MonsterBuild,
  MonsterColor,
  MonsterDna,
  MonsterSize,
  MouthShape,
  Pattern,
  Respiration,
  SocialBehavior,
  TailShape,
} from "@monsters/game-core";
